### ISSUE TITLE
Cannot be used on Windows

### ISSUE THREAD

**Issue by selimb** [typeddjango/pytest-mypy-plugins#13]
`capturer`, a dependency of this project, cannot be used on Windows, as it clearly states in the first paragraph of the [documentation](ttps://capturer.readthedocs.io/en/latest/).

Is `capturer` a hard requirement? As far as I can tell, it's only used in [typecheck_in_same_process](https://github.com/typeddjango/pytest-mypy-plugins/blob/master/pytest_mypy/item.py#L174) to  capture `mypy`'s output. However:
- Both `mypy.main.process_options` and `mypy.build.build` accept an optional `TextIO` for `stdout` and `stderr`. 
- `contextlib.redirect_stdout` and `contextlib.redirect_stderr` could be used here, since nothing runs in a subprocess (as far as I can tell? otherwise I don't see how `mypy` could even reliably support the parameters above)

I'd be happy to submit a PR, unless I've missed something.

**Comment by sobolevn** [comment]
@selimb sure! Thanks a lot.

**Comment by mkurnikov** [comment]
Fixed in https://github.com/typeddjango/pytest-mypy-plugins/pull/14
