### ISSUE TITLE
Support for older pytest

### ISSUE THREAD

**Issue by delfick** [typeddjango/pytest-mypy-plugins#150]
Hi, I'm wondering how important it is to you for this plugin to continue supporting pytest 6?

Is pytest 7/8 are old enough to warrant removing the code that makes this plugin compatible with pytest 6 or would you rather keep that support?

**Comment by sobolevn** [comment]
pytest6 is not relevant anymore, we should not keep any support for it.
Cleaner code, simplier workflow.

**Comment by delfick** [comment]
Awesome, I'll make a PR :)

**Comment by delfick** [comment]
@sobolevn also, speaking of compatibility. Python 3.8 is end of life in later in the year, do you want to keep support for it till then, or is it ok to remove support for it and be able to use [PEP 585](https://peps.python.org/pep-0585/) in this repo?

(Though, in finding that link I noticed that we can already make use of that with a `from __future__ import annotations` it seems)

**Comment by sobolevn** [comment]
Yes, we need 3.8 for now. `django-stubs` should drop it first.

**Comment by delfick** [comment]
ok, fair enough. The good news is it appears django 5 only supports python 3.10 and above, so I imagine django-stubs could maybe drop it soon?

**Comment by sobolevn** [comment]
yes, we will drop it as soon as it will reach EOL
