### ISSUE TITLE
AttributeError: type object 'YamlTestFile' has no attribute 'from_parent'  in pytest_collect_file

### ISSUE THREAD

**Issue by lovasoa** [typeddjango/pytest-mypy-plugins#28]
The latest update to pytest_mypy_plugins broke my CI tests with the following error

```
==================================== ERRORS ====================================

______________________ ERROR collecting tests/__init__.py ______________________

../../../virtualenv/python3.8.0/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__

    return self._hookexec(self, self.get_hookimpls(), kwargs)

../../../virtualenv/python3.8.0/lib/python3.8/site-packages/pluggy/manager.py:92: in _hookexec

    return self._inner_hookexec(hook, methods, kwargs)

../../../virtualenv/python3.8.0/lib/python3.8/site-packages/pluggy/manager.py:83: in <lambda>

    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(

../../../virtualenv/python3.8.0/lib/python3.8/site-packages/pytest_mypy_plugins/collect.py:139: in pytest_collect_file

    return YamlTestFile.from_parent(parent, fspath=path)

E   AttributeError: type object 'YamlTestFile' has no attribute 'from_parent'

!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!

=============================== 1 error in 0.11s ===============================

The command "pytest" exited with 2.
```

view the log outputs here: https://travis-ci.org/github/lovasoa/marshmallow_dataclass/jobs/705848682

**Comment by sobolevn** [comment]
What is your `pytest` version? It should be at least `5.4.`

**Comment by lovasoa** [comment]
I am using pytest v5.2.1. If you want to break compatibility with older pytest versions, can you please do so in a major version bump ? This should avoid automatic updates from breaking working tests. And could you please also document such backward-incompatible changes in the future ?

**Comment by kornicameister** [comment]
Yeah...sorry 🤭. Guess we did a small mistake with @sobolevn by avoiding backward compatibility. I wilk drop a PR later on with a fix.

**Comment by sobolevn** [comment]
This was intentional. I don't consider this a breaking change, because all package resolvers do handle this correctly. 

But, anyways, @lovasoa sorry for the inconvenience!

**Comment by lovasoa** [comment]
No problem, thanks for your quick answer 🙂

**Comment by kornicameister** [comment]
@sobolevn I should skip fixing that?

**Comment by sobolevn** [comment]
@kornicameister yes, this is fine 🙂 

Thanks a lot for your help! (Trying out `parametrized` to test out my HKT implementation!)
