### ISSUE TITLE
Does not work with mypy@0.710

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/pytest-mypy-plugins#3]
Source code: https://github.com/dry-python/returns/tree/master/typesafety

Error:

```
/home/travis/build/dry-python/returns/typesafety/test_result_types/safe.test:8: 
E   pytest_mypy.utils.TypecheckAssertionError: Invalid output: 
E   Expected:
E     main:7: error: Revealed type is 'def () -> returns.result.Result[builtins.int*, builtins.Exception]' (diff)
E   Actual:
E     main:7: note: Revealed type is 'def () -> returns.result.Result[builtins.int*, builtins.Exception]' (diff)
E   
E   Alignment of first line difference:
E     E: main:7: error: Revealed type is 'def () -> returns.result.Result[builtin...
E     A: main:7: note: Revealed type is 'def () -> returns.result.Result[builtins...
E                ^
```

Link to PR: https://github.com/dry-python/returns/pull/98
Link to CI: https://travis-ci.org/dry-python/returns/jobs/548053832

**Comment by sobolevn** [comment]
Basically it has changed its output from `error` to `note`

**Comment by mkurnikov** [comment]
Could you change lines in tests from `# E: Revealed type is ...` to `# N: Revealed type is ...` and see whether it helps? It should, just pushed https://github.com/mkurnikov/pytest-mypy-plugins/commit/d1fa0906e508a1dcca4cfb394fc89c003d8b74e7 which replaces those in tests and CI passes.
