### ISSUE TITLE
Output-file rewriting removes '.py' in too many places

### ISSUE THREAD

**Issue by aghast** [typeddjango/pytest-mypy-plugins#35]
The last line of  `pytest_mypy_plugins.items.replace_fpath_with_module_name()` does a blanket removal of all ".py" strings:

    return line.strip().replace(".py", "")

This destroys paths in log information when `mypy.verbosity > 0`. Paths like `"$HOME/.pyenv"` and `".../python3.6/.../__init__.pyi"` are converted into random strings.

I suspect you are only trying to replace `"main.py: 1: note: ..."` -type strings at the beginning of the line. If that is true (and I really haven't explored enough to be sure, so please check this) then a simple replacement my be `replace(".py:", ":")` to ensure the offending .py looks like a filespec. 

Otherwise maybe only do the replacement in the first colon-delimited field?

**Comment by sobolevn** [comment]
Hi! Thanks for the info!

Can you please provide a full example?

**Comment by aghast** [comment]
When I have these settings in a test .yaml file (note the `verbosity`):
```
  mypy_config: |
    [mypy]
    # !! IMPORTANT !!
    namespace_packages = True
    verbosity = 1
```

This line appears in my output:

    E     LOG:  Metadata fresh for genericpath: file /home/aghast/env/versions/3.6.9/envs/venv-aghast-utils/lib/python3.6/site-packages/mypy/typeshed/stdlib/2and3/genericpathi (diff)

I don't have a `env` directory under $HOME. But I do have a `.pyenv` directory. And I don't have a file named `.../2and3/genericpathi` but I do have one named `.../2and3/genericpath.pyi`.

The difference in both cases is that the `replace(".py", "")` is deleting too much.

**Comment by sobolevn** [comment]
Oh, now I get it! Thanks a lot! 👍

**Comment by aghast** [comment]
I thought about that, but there's no way to write a test for "this one line appears somewhere in the output". :( And when you enable `verbosity=1` you get a LOT of output...

**Comment by sobolevn** [comment]
We can really skip a test for it

**Comment by aghast** [comment]
:astonished: Step away from the keyboard! The TDD-police have been notified and will arrive shortly.

**Comment by sobolevn** [comment]
🚓 👮

They won't catch me! 😆
