### ISSUE TITLE
pdb not catching although --mypy-same-process

### ISSUE THREAD

**Issue by kornicameister** [typeddjango/pytest-mypy-plugins#49]
Hey @sobolevn, hope you're doing great in those crazy days !

Anyway, I want to keep this short. I am trying to debug a certain issue in my code but I have the problem.
Neither pycharm nor pdb is able to break in a place I want. It makes no difference whether I make a breakpoint or do `pdb.set_trace()`. It just ignores that.

Here's relevant portion of my setup https://github.com/kornicameister/axion/blob/master/pytest.ini#L9
Any hints are welcome.

**Comment by sobolevn** [comment]
Do you want to use `--pbd` flag from `mypy`? Am I right?

**Comment by kornicameister** [comment]
No, just want to drop myself into arbitrary piece of the code of the plugin I am testing.
Say [here](https://github.com/kornicameister/axion/blob/master/axion/oas_mypy/__init__.py#L133) for instance. So I do `import pdb; pdb.set_trace()` in that line and run a test but `pdb` does not stop there.

So it is neither about `mypy`'s `--pdb` nor `pytest`'s `--pdb` flags.
More like trying to set a breakpoint in visual tool (i.e. Pycharm)

**Comment by kornicameister** [comment]
I think, long story short, I just want to **debug** plugin's code.

**Comment by sobolevn** [comment]
Does `import pdb; pdb.set_trace()` work when running mypy directly?

**Comment by kornicameister** [comment]
Answer to you question is  `no`. 
`mypy` sees those instructions as normal code and it couldn't care less.

So you're basically saying that it wouldn't be possible to use debugger when pytest runs test case?

**Comment by sobolevn** [comment]
Looks like it is possible from the `mypy` itself: https://github.com/python/mypy/blob/7b7cce387dab99416d76fd4b10061dac3f7c1374/mypy/errors.py#L743-L746

But, it might be related to the fact that `mypy` is compiled with `mypyc` and is executed in the compiled mode.
You can try to install `mypy` source code directly and try debugging it again.

**Comment by kornicameister** [comment]
Ok, will try to see if that helps.

**Comment by kornicameister** [comment]
Oh for the love of god...actually, it turns out debugger is catching things up but it is not entering the code I want it to enter.
So for some reason it not seeing application own code. Hmmm...perhaps that is related to pythonpath.

Anyway, I am sorry for taking up your time. An error was on my end.

**Comment by kornicameister** [comment]
FYI and in the spirit of clarification: The pdb started to pick up where I wanted it to pick but only after I installed **my application** via `pip install -e .`. I think I've made rather stupid mistake here assuming that things will be just picked.

**Comment by sobolevn** [comment]
Thanks a lot for solving this 🙂
