### ISSUE TITLE
Add option to disable "--no-silent-site-packages`

### ISSUE THREAD

**Issue by yuyupopo** [typeddjango/pytest-mypy-plugins#50]
I've got the same problem shown in the comment https://github.com/typeddjango/pytest-mypy-plugins/issues/34#issuecomment-696836789

I've seen the code and I believe that this line https://github.com/typeddjango/pytest-mypy-plugins/blob/1c49b238bb316d9aac4db8e9bf072bf76742dd63/pytest_mypy_plugins/item.py#L299

causes mypy to type check all files in the site-packages. 

I believe that for local testing, it would be beneficial to turn it off. WDYT?
Adding this feature would be quite easy. e.g. `--mypy-only-local-stub` opt

You can try out this feature here: https://github.com/yuyupopo/pytest-mypy-plugins

**Comment by sobolevn** [comment]
Yes, this is a known issue: https://github.com/typeddjango/pytest-mypy-plugins/issues/34

Let's discuss it there! 👍 
And btw - PRs are welcome!
