### ISSUE TITLE
pystache is not maintained

### ISSUE THREAD

**Issue by orsinium** [typeddjango/pytest-mypy-plugins#52]
[pystache](https://github.com/defunkt/pystache) support stopped in 2014 without reaching a stable release. The project is unsupported, PRs are unmerged, issues unanswered, the only author doesn't have any activity on github since 2018. Depending on pystache is dangerous.

As an alternative, I'd recommend [Jinja2](https://github.com/pallets/jinja). Famous, well supported, in good hands of a nice community, has similar but more powerful syntax. However, if you really want the mustache syntax, [chevron](https://github.com/noahmorrison/chevron) is a good option: it is maintained and much faster.

**Comment by MatthieuDartiailh** [comment]
Since #57 has been merged this can be closed right ?

**Comment by orsinium** [comment]
Indeed! Thank you for pinging :)
