### ISSUE TITLE
regex not listed as a dependency in setup.py

### ISSUE THREAD

**Issue by MatthieuDartiailh** [typeddjango/pytest-mypy-plugins#60]
Currently regex is imported at https://github.com/typeddjango/pytest-mypy-plugins/blob/master/pytest_mypy_plugins/utils.py#L23 but it is not listed in setup.py 

I ran into the issue with 1.8 in a project https://github.com/nucleic/atom/pull/122/checks?check_run_id=3538057249

Would it be possible to fix it and publish a new release ?

**Comment by sobolevn** [comment]
@MatthieuDartiailh please, send a PR. I will publish new release ASAP.

**Comment by MatthieuDartiailh** [comment]
Done in #61. Thanks for the fast answer @sobolevn
