### ISSUE TITLE
Remove usage of distutils

### ISSUE THREAD

**Issue by zero323** [typeddjango/pytest-mypy-plugins#71]
`distutils` are deprecated in Python 3.10 and going to be removed in 3.12 ([PEP 632](https://www.python.org/dev/peps/pep-0632/)). 

Currently `distutils` are used in `pytest_mypy_plugins.item`:

https://github.com/typeddjango/pytest-mypy-plugins/blob/6c769da8876595b404ac59056f751affc9572c21/pytest_mypy_plugins/item.py#L199

to find `mypy` executable.

**Comment by sobolevn** [comment]
We can change it to `shutil.which`
Docs: https://www.python.org/dev/peps/pep-0632/#migration-advice

**Comment by zero323** [comment]
I was just working on a PR :)
