### ISSUE TITLE
Setting `--python-version` overrides option in `--mypy-ini-file`

### ISSUE THREAD

**Issue by antonagestam** [typeddjango/pytest-mypy-plugins#91]
I'm running into an issue where running `mypy` gives no errors, but `pytest-mypy-plugins` gets mypy errors due to it overriding `--python-version`. I'm setting `python_version = 3.7` for compatibility reasons, which causes an attribute error for `types.UnionType` [which I ignore](https://github.com/antonagestam/phantom-types/blob/fix/bump-mypy/src/phantom/utils.py#L140).

But because pytest-mypy-plugins [overrides the `python_version` set in config](https://github.com/typeddjango/pytest-mypy-plugins/blob/a17efc7/pytest_mypy_plugins/item.py#L313), in my case to 3.10 this causes mypy to think that `types.UnionType` is always there and yield and warning for the now unused ignore comment.

Naively I can't figure out why pytest-mypy-plugins needs to set `--python-version` at all. Perhaps it's worth considering not doing that?

As a less intrusive way forward, perhaps we could make it so that `--python-version` is only set when no ini config file is given?

**Comment by sobolevn** [comment]
@antonagestam 

> Naively I can't figure out why pytest-mypy-plugins needs to set --python-version at all. Perhaps it's worth considering not doing that?

I think the initial idea was to ensure that we have the same python version that we are running on.

But, I don't like this decision. Let's remove it.
Do you want to send a PR?

P.S. Happy New Year!
